### ISSUE TITLE
Use different map source from Wikipedia

### ISSUE THREAD

**Issue by kaihendry** [kaihendry/mrt#3]
https://commons.wikimedia.org/wiki/User:Aforl

Licensed under  Creative Commons Attribution-Share Alike 3.0 Unported and best of all, you can actually select the text!

**Comment by cheeaun** [comment]
:scream: :+1:

**Comment by kaihendry** [comment]
I'm confused. When I open https://upload.wikimedia.org/wikipedia/commons/6/68/Singapore_MRT_and_LRT_System_Map.svg I can make text selections...  

<img src=http://s.natalian.org/2015-09-13/1442112670_1246x1058.png>

But once embedded in a Web page I can't. What the hell! :(

**Comment by miccheng** [comment]
Its an image when embedded.

**Comment by kaihendry** [comment]
I understand that. So that means (I guess) that it can't be interacted with.

How does one work around that ?

**Comment by jakearchibald** [comment]
Include the SVG directly into the page (see the diagrams in https://jakearchibald.com/2015/anatomy-of-responsive-images/), or embed it as an iframe (see the flowchart in http://www.html5rocks.com/en/tutorials/forms/requestautocomplete/).
